/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.googlecast;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.os.Looper;
import android.os.Message;
import android.support.v7.media.MediaControlIntent;
import android.support.v7.media.MediaRouter;
import android.support.v7.media.MediaRouter.RouteInfo;

import com.google.android.gms.cast.CastMediaControlIntent;

@Kroll.proxy(creatableInModule = ChromecastModule.class)
public class RouteInfoProxy extends KrollProxy {
	private static final String LCAT = ChromecastModule.LCAT;

	public RouteInfo route;
	private static final int MSG_FIRST_ID = KrollModule.MSG_LAST_ID + 1;
	private static final int MSG_SELECT = MSG_FIRST_ID + 100;
	private static final int MSG_START = MSG_FIRST_ID + 101;

	public RouteInfoProxy() {
		super();

	}

	public RouteInfoProxy(RouteInfo route) {
		super();
		if (route instanceof RouteInfo)
			this.route = (RouteInfo) route;
		else
			Log.e(LCAT, "Unable to create RouteInfoProxy. Invalid type.");

	}

	@Kroll.method
	public String getName() {
		return this.route.getName();
	}

	@Kroll.method
	public String getDescription() {
		return this.route.getDescription();
	}

	@Kroll.method
	public String getId() {
		return this.route.getId();
	}

	@Kroll.method
	public boolean isSelected() {
		return this.route.isSelected();
	}

	@Kroll.method
	public String getIcon() {
		Uri uri = this.route.getIconUri();
		return (uri == null) ? null : uri.toString();
	}

	@Kroll.method
	public KrollDict getExtras() {
		KrollDict kd = new KrollDict();
		/*
		 * Bundle bundle = this.route.getExtras(); if (bundle != null) for
		 * (String key : bundle.keySet()) { // kd.put(key, true);//
		 * bundle.get(key).toString()); // To // Implement }
		 */
		return kd;
	}

	@Kroll.method
	public KrollDict getDeviceType() {
		KrollDict kd = new KrollDict();
		kd.put("type", this.route.getDeviceType());
		switch (this.route.getDeviceType()) {
		case MediaRouter.RouteInfo.DEVICE_TYPE_BLUETOOTH:
			kd.put("typeName", "BLUETOOTH");
			break;
		case MediaRouter.RouteInfo.DEVICE_TYPE_SPEAKER:
			kd.put("typeName", "SPEAKER");
			break;
		case MediaRouter.RouteInfo.DEVICE_TYPE_TV:
			kd.put("typeName", "IV");
			break;
		case MediaRouter.RouteInfo.DEVICE_TYPE_UNKNOWN:
			kd.put("typeName", "UNKNOWN");
			break;
		}
		return kd;
	}

	@Kroll.method
	public KrollDict getConnectionState() {
		KrollDict kd = new KrollDict();
		kd.put("state", this.route.getConnectionState());
		switch (this.route.getConnectionState()) {
		case MediaRouter.RouteInfo.CONNECTION_STATE_CONNECTED:
			kd.put("stateName", "CONNECTED");
			break;
		case MediaRouter.RouteInfo.CONNECTION_STATE_DISCONNECTED:
			kd.put("stateName", "DISCONNECTED");
			break;
		case MediaRouter.RouteInfo.CONNECTION_STATE_CONNECTING:
			kd.put("stateName", "CONNECTING");
			break;

		}
		return kd;
	}

	@Kroll.method
	public boolean isEnabled() {
		return this.route.isEnabled();
	}

	// Setters:
	@Kroll.method
	public void select() {
		getMainHandler().obtainMessage(MSG_SELECT).sendToTarget();
	}

	@Kroll.method
	public void playRemotePlayback(String uri) {
		Bundle bundle = new Bundle();
		bundle.putString("uri", uri);
		bundle.putBoolean("live", false);
		bundle.putBoolean("enqueue", false);
		getMainHandler().obtainMessage(MSG_START, bundle).sendToTarget();
	}

	@Kroll.method
	public void enqueueRemotePlayback(String uri) {
		Bundle bundle = new Bundle();
		bundle.putString("uri", uri);
		bundle.putBoolean("enqueue", true);
		getMainHandler().obtainMessage(MSG_START, bundle).sendToTarget();
	}

	@Kroll.method
	public void playLiveAudio(String uri) {
		Bundle bundle = new Bundle();
		bundle.putString("uri", uri);
		bundle.putBoolean("live", true);
		getMainHandler().obtainMessage(MSG_START, bundle).sendToTarget();
	}

	@Kroll.method
	public void playLiveVideo(String uri) {
		Bundle bundle = new Bundle();
		bundle.putString("uri", uri);
		bundle.putBoolean("live", true);
		bundle.putBoolean("video", true);
		getMainHandler().obtainMessage(MSG_START, bundle).sendToTarget();
	}

	private void handleSendControlRequest(Bundle bundle) {
		checkCallingThread();
		boolean enqueue = bundle.containsKey("enqueue") ? true : false;
		boolean live = bundle.containsKey("live") ? true : false;
		boolean video = bundle.containsKey("video") ? true : false;
		String uri = bundle.getString("uri");

		Intent intent = new Intent(MediaControlIntent.ACTION_START_SESSION);
		if (!live)
			intent.addCategory(MediaControlIntent.CATEGORY_REMOTE_PLAYBACK);

		intent.putExtra(CastMediaControlIntent.EXTRA_CAST_APPLICATION_ID,
				CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID);

		intent.putExtra(CastMediaControlIntent.EXTRA_CAST_RELAUNCH_APPLICATION,
				true);
		intent.putExtra(CastMediaControlIntent.EXTRA_DEBUG_LOGGING_ENABLED,
				true);
		intent.putExtra(
				CastMediaControlIntent.EXTRA_CAST_STOP_APPLICATION_WHEN_SESSION_ENDS,
				true);
		this.route.sendControlRequest(intent,
				new MediaRouter.ControlRequestCallback() {
					@Override
					public void onResult(Bundle data) {
						super.onResult(data);
						String sessionId = data
								.getString(MediaControlIntent.EXTRA_SESSION_ID);
					}

					@Override
					public void onError(String error, Bundle data) {
						super.onError(error, data);
					}
				});
	}

	@Kroll.method
	public boolean canDisconnect() {
		return this.route.canDisconnect();
	}

	@Override
	public boolean handleMessage(Message msg) {
		switch (msg.what) {
		case MSG_SELECT: {
			this.route.select();
			return true;
		}
		case MSG_START: {
			Bundle bundle = (Bundle) (msg.obj);
			handleSendControlRequest(bundle);
			return true;
		}
		default: {
			return super.handleMessage(msg);
		}
		}
	}

	static void checkCallingThread() {
		if (Looper.myLooper() != Looper.getMainLooper()) {
			throw new IllegalStateException(
					"The media router service must only be "
							+ "accessed on the application's main thread.");
		}
	}

	@Kroll.method
	public String getApiName() {
		return "ti.chromecast.RouteInfo";
	}
}