/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.chromecast;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

//import android.app.Activity;

@Kroll.module(name = "Tichromecast", id = "ti.chromecast")
public class ChromecastModule extends KrollModule {
	public ChromecastModule() {
		super();
	}

	// @Override
	// public void onStart(Activity activity) {
	// super.onStart(activity);
	// }
}
