/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.chromecast;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import android.content.Context;
import android.os.Message;
import android.support.v7.media.MediaControlIntent;
import android.support.v7.media.MediaRouteSelector;
import android.support.v7.media.MediaRouter;
import android.support.v7.media.MediaRouter.Callback;

import com.google.android.gms.cast.CastMediaControlIntent;

@Kroll.proxy(creatableInModule = ChromecastModule.class)
public class DeviceManagerProxy extends KrollProxy {
	// Standard Debugging variables
	private static final String LCAT = "TCC";

	@SuppressWarnings("unused")
	private MediaRouter mediaRouter;
	private MediaRouteSelector mediaRouteSelector;
	private static final int MSG_FIRST_ID = KrollModule.MSG_LAST_ID + 1;
	private static final int MSG_MEDIAROUTER_START = MSG_FIRST_ID + 100;
	protected static final int MSG_LAST_ID = MSG_FIRST_ID + 999;

	@Override
	public boolean handleMessage(Message msg) {
		switch (msg.what) {
		case MSG_MEDIAROUTER_START: {
			Context context = TiApplication.getInstance()
					.getApplicationContext();
			mediaRouter = MediaRouter.getInstance(context);
			return true;
		}
		default: {
			return super.handleMessage(msg);
		}
		}
	}

	public DeviceManagerProxy() {
		super();
		Log.d(LCAT, "init DeviceManagerProxy");
	}

	@Kroll.method
	public MediaRouteSelector getMediaRouteSelector(String AppID) {
		MediaRouteSelector selectorBuilder = new MediaRouteSelector.Builder()
				.addControlCategory(MediaControlIntent.CATEGORY_LIVE_VIDEO)
				.addControlCategory(MediaControlIntent.CATEGORY_REMOTE_PLAYBACK)
				.build();
		/**/
		MediaRouter mediaRouter = MediaRouter.getInstance(TiApplication
				.getInstance().getApplicationContext());
		MediaRouteSelector selector = null;
		Callback callback = null;
		mediaRouter.addCallback(selector, callback,
				MediaRouter.CALLBACK_FLAG_REQUEST_DISCOVERY);
		// forces to Main thread:
		getMainHandler().obtainMessage(MSG_MEDIAROUTER_START).sendToTarget();

		// getting appid from cromecast receiver:
		String mAppID = (AppID.equals("DEFAULT_MEDIA_RECEIVER")) ? mAppID = CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID
				: AppID;
		Log.d(LCAT, "AppId========" + mAppID);
		// Configure Cast device discovery

		try {
			mediaRouteSelector = new MediaRouteSelector.Builder()
					.addControlCategory(
							CastMediaControlIntent.categoryForCast(mAppID))
					.build();
		} catch (Exception e) {
			Log.e(LCAT, "exception: " + e.getMessage());

		}
		return mediaRouteSelector;
	}
}